<div id="search-bar">
	<div class="container">
            <div id="type_filter">
                <a href="#">All</a>
                <?php foreach($this->user['availableTypes'] as $type){ ?>
                    <a href="#"><?php echo $type; ?></a>
                <?  } ?>
            </div>
            <ul id="active-filters">
                <?php foreach($this->users['brands'] as $brand){ ?>
                    <!-- <li class="<?php echo $brand; ?>"><span class="close"></span><?php echo $brand; ?></li> -->
                <? } ?>
            </ul>
            <div id="gender-toggle" class="right">
                <a href="/female" class="<?php if($_SESSION['user']['gender'] == 'f'){ echo "active"; } ?>" data-gender="f">Female</a>
                |
                <a href="/male" class="<?php if($_SESSION['user']['gender'] == 'm'){ echo "active"; } ?>" data-gender="m">Male</a>
            </div>    
		<!-- <div id="search" class="ui-widget">
			<form>
				<input type="text" name="query" id="query" placeholder="Add a Brand" />
			</form>
		</div> -->
	</div>
</div><!--#search-->
<div class="container">
    
</div>

<div class="clear"></div>

<div id="splash"></div>

<div class="indicator"></div>

<ul id="products"></ul>

<div id="womens-styles-cont">
	<h1>Choose your style</h1> 
	<ul class="style-choices" id="womens-styles">
		<li class="All">
			<img src="/img/women-1.jpg" alt="All Brands" />
			<div class="btn-container"><button class="gray-large">All Styles</button></div>
		</li>
		<li class="Random">
			<img src="/img/halloween/style-woman-random.jpg" alt="Random" />
			<div class="btn-container"><button class="gray-large">Random</button></div>
		</li>
		<li class="Scary">
			<img src="/img/halloween/style-woman-scary.jpg" alt="Scary" />
			<div class="btn-container"><button class="gray-large">Scary</button></div>
		</li>
		<li class="Role">
			<img src="/img/halloween/style-woman-occupation.jpg" alt="Role" />
			<div class="btn-container"><button class="gray-large">Role</button></div>
		</li>
		<li class="Sexy">
			<img src="/img/halloween/style-woman-sexy.jpg" alt="Sexy" />
			<div class="btn-container"><button class="gray-large">Sexy</button></div>
		</li>
        <li class="Movie">
			<img src="/img/halloween/style-woman-movie.jpg" alt="Movie" />
			<div class="btn-container"><button class="gray-large">Movie</button></div>
		</li>
        <li class="Funny">
			<img src="/img/halloween/style-woman-funny.jpg" alt="Funny" />
			<div class="btn-container"><button class="gray-large">Funny</button></div>
		</li>
		<div class="clear"></div>
	</ul>
</div>

<div id="mens-styles-cont">
	<h1>Choose your style</h1> 
	<ul class="style-choices" id="mens-styles">
		<li class="All">
			<img src="/img/man-1.jpg" alt="All Brands" />
			<div class="btn-container"><button class="gray-large">All Brands</button></div>
		</li>
		<li class="Random">
			<img src="/img/halloween/style-man-random.jpg" alt="Random" />
			<div class="btn-container"><button class="gray-large">Random</button></div>
		</li>
		<li class="Scary">
			<img src="/img/halloween/style-man-scary.jpg" alt="Scary" />
			<div class="btn-container"><button class="gray-large">Scary</button></div>
		</li>
		<li class="Role">
			<img src="/img/halloween/style-man-occupation.jpg" alt="Role" />
			<div class="btn-container"><button class="gray-large">Role</button></div>
		</li>
		<li class="Movie">
			<img src="/img/halloween/style-man-movie.jpg" alt="Movie" />
			<div class="btn-container"><button class="gray-large">Movie</button></div>
		</li>
		<li class="Funny">
			<img src="/img/halloween/style-man-funny.jpg" alt="Funny" />
			<div class="btn-container"><button class="gray-large">Funny</button></div>
		</li>
		<div class="clear"></div>
	</ul>
</div>

<div id="lightbox-gender">
	<h2>PICK ONE.</h2>
	<div class="gender-option female"></div>
	<div class="gender-option male"></div>
</div>
<div id="lightbox-product">
	<div class="close" id="lp-close"></div>
	<div class="lp-img-full"><a href=""><img src="" alt="test" /></a></div>
	<div class="lp-content-right">
		<div class="lp-name"></div>
		<div class="lp-brand"></div>
		<div class="lp-price-cont">
			<div class="lp-price-left"></div>
			<div class="lp-price"></div>
			<div class="clear"></div>
		</div>
		<p class="lp-desc"></p>
		<a href="" target="_blank"><button class="lp-buy">BUY IT</button></a>
	</div>
	<div id="lp-comments"></div>
</div>
<div id="dimmer"></div>
<div id="styles-btn"></div>
<div id="back-btn" class="hide">BACK</div>
<script type="text/javascript">
	var app = {
	    user: <?php echo json_encode($_SESSION['user']); ?>,
            skip_wizard: <?php echo ($this->skip_wizard)? $this->skip_wizard: 0; ?>,
            productPage: 0,
            type_fitlers: '',
	    init: function(){
                this.type_filters = $('#type_filter');
                if( this.skip_wizard ){
	            this.hide_wizard();
	            this.update_products();
                    this.endless_scroll();
                }else if( typeof this.user.gender != 'undefined' && typeof this.user.style != 'undefined' ){
                    this.hide_wizard();
                    this.update_products();
                    this.endless_scroll();
                }
	    },
            hide_wizard: function(){
                $('#dimmer').hide();
                $('#lightbox-gender').hide();
                $('#splash').hide();
                $('.indicator').show();

                $('#search-bar').show();
                $('.indicator').show();
                $('#type_filter').show();
                $('#styles-btn').show();
                $('#back-btn').removeClass('hide');
            },
            update_products: function(){
                var t = this;
                $.ajax({
                    url: '/api/products',
                    type: 'post',
                    data: { 'page': this.productPage },
                    success: function(res){
                        var $container = $('#products');
                        $container.html(res.result.html).show().css({visibility:'hidden'});
                         $container.imagesLoaded(function(){
                            $('.indicator').hide();
                            $container.masonry('reload').css({visibility:'visible'});
                            $('#styles-btn').show();
                            $('#back-btn').removeClass('hide');
                            $('#type_filter').show();
                         });
                    }
                });
                $.get('/api/get-user', function(res){
                    t.active_filters = $('#active-filters');
                    t.active_filters.html('');
                    
                    $(res.result.brands).each( function(k,v){
                        t.add_brand(v);
                    });
                    
                    t.type_filters = $('#type_filter');
                    t.type_filters.html('');
                    res.result.availableStyles.unshift('All');
                    $(res.result.availableStyles).each( function(k,v){
                        t.add_filter_type(v,res.result.style);
                        console.log(v);
                        console.log(res.result.type);
                    });
                }, 'json');
            },
            endless_scroll: function(){
                var t = this;
            
                $(document).endlessScroll({
                  inflowPixels: 100,
                  fireDelay: true,
                  ceaseFireOnEmpty: false,
                  callback: function(i, x, direction) {
                    if (direction == 'prev') {
                        return false;
                    } else {
                        t.productPage++
                        t.append_products();
                    }
                  }
                });
            },
            append_products: function(){
                $.ajax({
                    url: '/api/products',
                    type: 'post',
                    data: { 'page': this.productPage },
                    success: function(res){
                        var $container = $('#products');
                        //$container.append(res.result.html).show().css({visibility:'hidden'});
                        $html = $(res.result.html);
                        $container.append($html);
                         $container.imagesLoaded(function(){
                            $('.indicator').hide();
                            $container.masonry('appended', $html);
                            $('#styles-btn').show();
                            $('#back-btn').removeClass('hide');
                            $('#type_filter').show();
                         });
                    }
                });
            },
            add_filter_type: function(type, user_type){
                if(user_type == type){
                    hit = 'class="hit"';
                }else{
                    hit = '';
                }
                html = '<a href="#"' + hit + '>' + type + '</a>';
                this.type_filters.append(html);
            },
            add_brand: function(brand){
                $active_filters = $('#active-filters');
                html = '<li class="' + brand + '"><span class="close"></span>' + brand + '</li>';
                $active_filters.append(html);
            }
	}
</script>