<div class="container">
    
</div>

<div class="clear"></div>

<div id="splash"></div>

<div class="indicator"></div>

<ul id="products"></ul>

<div id="womens-styles-cont">
	<h1>Choose your style</h1> 
	<ul class="style-choices" id="womens-styles">
		<li class="All">
			<img src="/img/women-1.jpg" alt="All Brands" />
			<div class="btn-container"><button class="gray-large">All Styles</button></div>
		</li>
		<li class="Random">
			<img src="/img/halloween/style-woman-random.jpg" alt="Random" />
			<div class="btn-container"><button class="gray-large">Random</button></div>
		</li>
		<li class="Scary">
			<img src="/img/halloween/style-woman-scary.jpg" alt="Scary" />
			<div class="btn-container"><button class="gray-large">Scary</button></div>
		</li>
		<li class="Role">
			<img src="/img/halloween/style-woman-occupation.jpg" alt="Role" />
			<div class="btn-container"><button class="gray-large">Role</button></div>
		</li>
		<li class="Sexy">
			<img src="/img/halloween/style-woman-movie.jpg" alt="Sexy" />
			<div class="btn-container"><button class="gray-large">Sexy</button></div>
		</li>
        <li class="Movie">
			<img src="/img/halloween/style-woman-movie.jpg" alt="Movie" />
			<div class="btn-container"><button class="gray-large">Movie</button></div>
		</li>
        <li class="Funny">
			<img src="/img/halloween/style-woman-funny.jpg" alt="Funny" />
			<div class="btn-container"><button class="gray-large">Funny</button></div>
		</li>
		<div class="clear"></div>
	</ul>
</div>

<div id="mens-styles-cont">
	<h1>Choose your style</h1> 
	<ul class="style-choices" id="mens-styles">
		<li class="All">
			<img src="/img/man-1.jpg" alt="All Brands" />
			<div class="btn-container"><button class="gray-large">All Brands</button></div>
		</li>
		<li class="Random">
			<img src="/img/halloween/style-man-random.jpg" alt="Random" />
			<div class="btn-container"><button class="gray-large">Random</button></div>
		</li>
		<li class="Scary">
			<img src="/img/halloween/style-man-scary.jpg" alt="Scary" />
			<div class="btn-container"><button class="gray-large">Scary</button></div>
		</li>
		<li class="Role">
			<img src="/img/halloween/style-man-scary.jpg" alt="Role" />
			<div class="btn-container"><button class="gray-large">Role</button></div>
		</li>
		<li class="Movie">
			<img src="/img/halloween/style-man-movie.jpg" alt="Movie" />
			<div class="btn-container"><button class="gray-large">Movie</button></div>
		</li>
		<li class="Funny">
			<img src="/img/halloween/style-man-funny.jpg" alt="Funny" />
			<div class="btn-container"><button class="gray-large">Funny</button></div>
		</li>
		<div class="clear"></div>
	</ul>
</div>

<div id="lightbox-gender">
	<h2>PICK ONE.</h2>
	<div class="gender-option female"></div>
	<div class="gender-option male"></div>
</div>
<div id="dimmer"></div>
<div id="styles-btn"></div>
<div id="back-btn" class="hide">BACK</div>
<div class="container">
	<div id="footer">
		&copy; 2012 99styles. All rights reserved. 
	</div>
<script type="text/javascript">
	var app = {
	    user: <?php echo json_encode($_SESSION['user']); ?>,
	    init: function(){
	        if(typeof this.user.gender != 'undefined' && typeof this.user.style != 'undefined'){
	            $('#dimmer').hide();
	            $('#lightbox-gender').hide();
	            $('#splash').hide();
	            $('.indicator').show();
	            update_products();
	        }else{
	        }
	    }
	}

	//app.init();
</script>