<header>
	<div class="container">
		<a id="logo" href="/"></a>
		<div id="halloween-banner"></div>
		<div id="header-menu">
			<a href="http://twitter.com/99stylescom" target="_blank" title="Follow Us" id="twitter-icon"></a>
			<a href="http://www.facebook.com/99styles" target="_blank" title="Like Us" id="facebook-icon"></a> 
                    <?php if($this->users['member'] != 1){ ?>
                        <a href="https://www.facebook.com/dialog/oauth?client_id=<?php echo FACEBOOK_APPID; ?>&redirect_uri=<?php echo FACEBOOK_REDIRECTURI;?>&scope=<?php echo FACEBOOK_SCOPE; ?>"><strong>Login / Register</strong></a> 
                    <?}else{?>
                        <a href="/user/logout">Logout</a>
                    <?}?>
                    <a href="#">About</a>
		</div>
	</div>
</header>
<div id="search-bar">
	<div class="container">
            <div id="type_filter"><a href="#">All</a>
                <?php foreach($this->user['availableTypes'] as $type){ ?>
                <a href="#"><?php echo $type; ?></a>
                <?  } ?>
            </div>
		<ul id="active-filters">
                    <?php foreach($this->users['brands'] as $brand){ ?>
			<!-- <li class="<?php echo $brand; ?>"><span class="close"></span><?php echo $brand; ?></li> -->
                    <? } ?>
		</ul>
		<!-- <div id="search" class="ui-widget">
			<form>
				<input type="text" name="query" id="query" placeholder="Add a Brand" />
			</form>
		</div> -->
	</div>
</div><!--#search-->
<div class="container">
    
</div>

<div class="clear"></div>

<div id="splash"></div>

<div class="indicator"></div>

<ul id="products"></ul>

<div id="womens-styles-cont">
	<h1>Choose your style</h1> 
	<ul class="style-choices" id="womens-styles">
		<li class="All">
			<img src="/img/women-1.jpg" alt="All Brands" />
			<div class="btn-container"><button class="gray-large">All Styles</button></div>
		</li>
		<li class="Random">
			<img src="/img/halloween/style-woman-random.jpg" alt="Random" />
			<div class="btn-container"><button class="gray-large">Random</button></div>
		</li>
		<li class="Scary">
			<img src="/img/halloween/style-woman-scary.jpg" alt="Scary" />
			<div class="btn-container"><button class="gray-large">Scary</button></div>
		</li>
		<li class="Role">
			<img src="/img/halloween/style-woman-occupation.jpg" alt="Role" />
			<div class="btn-container"><button class="gray-large">Role</button></div>
		</li>
		<li class="Sexy">
			<img src="/img/halloween/style-woman-movie.jpg" alt="Sexy" />
			<div class="btn-container"><button class="gray-large">Sexy</button></div>
		</li>
        <li class="Movie">
			<img src="/img/halloween/style-woman-movie.jpg" alt="Movie" />
			<div class="btn-container"><button class="gray-large">Movie</button></div>
		</li>
        <li class="Funny">
			<img src="/img/halloween/style-woman-funny.jpg" alt="Funny" />
			<div class="btn-container"><button class="gray-large">Funny</button></div>
		</li>
		<div class="clear"></div>
	</ul>
</div>

<div id="mens-styles-cont">
	<h1>Choose your style</h1> 
	<ul class="style-choices" id="mens-styles">
		<li class="All">
			<img src="/img/man-1.jpg" alt="All Brands" />
			<div class="btn-container"><button class="gray-large">All Brands</button></div>
		</li>
		<li class="Random">
			<img src="/img/halloween/style-man-random.jpg" alt="Random" />
			<div class="btn-container"><button class="gray-large">Random</button></div>
		</li>
		<li class="Scary">
			<img src="/img/halloween/style-man-scary.jpg" alt="Scary" />
			<div class="btn-container"><button class="gray-large">Scary</button></div>
		</li>
		<li class="Role">
			<img src="/img/halloween/style-man-scary.jpg" alt="Role" />
			<div class="btn-container"><button class="gray-large">Role</button></div>
		</li>
		<li class="Movie">
			<img src="/img/halloween/style-man-movie.jpg" alt="Movie" />
			<div class="btn-container"><button class="gray-large">Movie</button></div>
		</li>
		<li class="Funny">
			<img src="/img/halloween/style-man-funny.jpg" alt="Funny" />
			<div class="btn-container"><button class="gray-large">Funny</button></div>
		</li>
		<div class="clear"></div>
	</ul>
</div>

<div id="lightbox-gender">
	<h2>PICK ONE.</h2>
	<div class="gender-option female"></div>
	<div class="gender-option male"></div>
</div>
<div id="dimmer"></div>
<div id="styles-btn"></div>
<div id="back-btn" class="hide">BACK</div>
<div class="container">
	<div id="footer">
		&copy; 2012 99styles. All rights reserved. 
	</div>
<script type="text/javascript">
	var app = {
	    user: <?php echo json_encode($_SESSION['user']); ?>,
	    init: function(){
	        if(typeof this.user.gender != 'undefined' && typeof this.user.style != 'undefined'){
	            $('#dimmer').hide();
	            $('#lightbox-gender').hide();
	            $('#splash').hide();
	            $('.indicator').show();
	            update_products();
	        }else{
	        }
	    }
	}

	//app.init();
</script>