<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title><?php echo $this->title; ?></title>
<script type="text/javascript" src="http://fast.fonts.com/jsapi/38ec39dc-f5f2-4978-9f2b-91e9833af949.js"></script><script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-35429774-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


</head>
<body>

<div id="wrapper">
    <header>
	<div class="container">
		<a id="logo" href="/"></a>
		<div id="halloween-banner"></div>
		<div id="header-menu">
                     <?php if($this->users['member'] != 1){ ?>
                        <a href="https://www.facebook.com/dialog/oauth?client_id=<?php echo FACEBOOK_APPID; ?>&redirect_uri=<?php echo FACEBOOK_REDIRECTURI;?>&scope=<?php echo FACEBOOK_SCOPE; ?>"><strong>Login / Register</strong></a> 
                    <?}else{?>
                        <a href="/user/logout">Logout</a>
                    <?}?><br><br>
                    <a href="http://twitter.com/99stylescom" target="_blank" title="Follow Us" id="twitter-icon"></a>
                    <a href="http://www.facebook.com/99styles" target="_blank" title="Like Us" id="facebook-icon"></a> 
                    <a href="#">About</a>
		</div>
	</div>
</header>
<div id="search-bar">
	<div class="container">
            <div id="type_filter"><a href="#">All</a>
                <?php foreach($this->user['availableTypes'] as $type){ ?>
                <a href="#"><?php echo $type; ?></a>
                <?  } ?>
            </div>
		<ul id="active-filters">
                    <?php foreach($this->users['brands'] as $brand){ ?>
			<!-- <li class="<?php echo $brand; ?>"><span class="close"></span><?php echo $brand; ?></li> -->
                    <? } ?>
		</ul>
		<!-- <div id="search" class="ui-widget">
			<form>
				<input type="text" name="query" id="query" placeholder="Add a Brand" />
			</form>
		</div> -->
	</div>
</div><!--#search-->
<?php echo $this->layout()->content; ?>
</div>

<?php if(APPLICATION_ENV == "prod"){ ?>
    <script type='text/javascript' src='/steal/steal.production.js?assistant'></script>
<? }else{ ?>
    <script type='text/javascript' src='/steal/steal.js?assistant'></script>
<?  }   ?>
</body>
</html>
