<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title><?php echo $this->title; ?></title>
<link type="text/css" rel="stylesheet" href="http://fast.fonts.com/cssapi/38ec39dc-f5f2-4978-9f2b-91e9833af949.css"/>
<link rel="stylesheet" type="text/css" href="/css/style.css">
<script type="text/javascript" src="/jquery/jquery.js"></script>
<script type="text/javascript" src="/jquery/jquery.masonry.js"></script>

</head>
<body>

<div id="wrapper">
<?php echo $this->layout()->content; ?>
</div>
    <script>
        $(document).ready(function(){
            var $container = $('#products');
            $container.imagesLoaded(function(){
		$container.masonry({
			itemSelector: 'li',
			columnWidth: 90
		});
            });
        });
        
        </script>
</body>
</html>