<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title><?php echo $this->title; ?></title>
<script type="text/javascript" src="http://fast.fonts.com/jsapi/38ec39dc-f5f2-4978-9f2b-91e9833af949.js"></script><script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-35429774-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>
<body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=383340111746969";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="wrapper">
  <header>
    <div class="container">
      <a id="logo" href="/"></a>
      <div id="halloween-banner"></div>
      <div id="header-menu">
        <?php /* if($this->users['member'] != 1){ ?>
          <a href="https://www.facebook.com/dialog/oauth?client_id=<?php echo FACEBOOK_APPID; ?>&redirect_uri=<?php echo FACEBOOK_REDIRECTURI;?>&scope=<?php echo FACEBOOK_SCOPE; ?>"><strong>Login / Register</strong></a> 
        <? } else { ?>
          <a href="/user/logout">Logout</a>
        <? } ?><br><br> */ ?>
        <strong style="color: orange;">Beta</strong>
        <a href="http://twitter.com/99stylescom" target="_blank" title="Follow Us" id="twitter-icon"></a>
        <a href="http://www.facebook.com/99styles" target="_blank" title="Like Us" id="facebook-icon"></a> <br /> <br />
        <a href="/about">About / Contact</a>
      </div>
    </div>
  </header>

<?php echo $this->layout()->content; ?>

<?php if(APPLICATION_ENV == "prod"){ ?>
    <script type='text/javascript' src='/steal/steal.production.js?assistant'></script>
<? }else{ ?>
    <script type='text/javascript' src='/steal/steal.js?assistant'></script>
<?  }   ?>
</body>
</html>
