<div id="page-cont">
	<div id="page-content">
		<img src="/img/logo-large.png" alt="99styles" /><br /><br />
		<p>99styles.com aims to bring a new shopping experience to the web that makes it easy for consumers of all ages to find clothes from all over the internet that match their individual styles.</p>
		<p><a href="/privacy-policy">Privacy Policy</a></p>
	</div><!-- #page-content -->
	<div id="contact-sidebar">
		<h2>Contact Us</h2>
		<p>For additional information or to contact our sales department email us at <a href="mailto:info@99styles.com">info@99styles.com</a></p>
	</div>
</div><!-- #page-cont -->