<?php
$params = $this->data;
?>
<div class="left" style="width:20%;">

	<div class="content">

		<div>
			<h4><a href="/admin/products"><-- Back to products</a></h4>
		</div>
	</div>

</div>

<div class="left">

	<div class="content">

		<div class="page-header">
		  <h3>
		  	<?php if($this->params('id')){ ?>
		  		Update <?php echo strtolower($this->model); ?>
		  	<?php }else { ?>
		  		Add <?php echo strtolower($this->model); ?>
		  	<?php } ?>
		  </h3>
		</div>

		<div class="row">
		  	<div class="span12">
		  		<form class="trig_save" action="/admin/data" method="POST">
		  			<input type="hidden" name="model" value="<?php echo $this->model; ?>">
                                        <input type="hidden" name="redir" value="<?php echo $this->params('redir'); ?>">
		  			<input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">

			        <fieldset>

						<legend><a name="basic_info"></a> Basic info</legend>
                                                <div class="clearfix">
							<label for="xlInput">Gender</label>
							<div class="input">
								<input class='large disabled' name='gender' value="<?php echo $params['gender']; ?>" type='text'>
							</div>
						</div>
                                                
                                                <div class="clearfix">
							<label for="xlInput">Theme</label>
							<div class="input">
								<input class='large disabled' name='theme' value="<?php echo $params['theme']; ?>" type='text'>
							</div>
						</div>
                                                
                                                <div class="clearfix">
							<label for="xlInput">Style</label>
							<div class="input">
								<input class='large disabled' name='style' value="<?php echo $params['style']; ?>" type='text'>
							</div>
						</div>
                                                
                                                <div class="clearfix">
							<label for="xlInput">Price</label>
							<div class="input">
								<input class='large disabled' name='price' value="<?php echo $params['price']; ?>" type='text'>
							</div>
						</div>
                                                
						<div class="clearfix">
							<label for="xlInput">Type</label>
							<div class="input">
								<input class='large disabled' name='type' value="<?php echo $params['type']; ?>" type='text'>
							</div>
						</div>
                                                
                                                <div class="clearfix">
							<label for="xlInput">Brand</label>
							<div class="input">
								<input class='large disabled' name='brand' value="<?php echo $params['brand']; ?>" type='text'>
							</div>
						</div>
                                                
                                                <div class="clearfix">
							<label for="xlInput">Image Url</label>
							<div class="input">
								<input class='large disabled' name='image_url' value="<?php echo $params['image_url']; ?>" type='text'>
                                                                <br/><a href="<?php echo $params['image_url']; ?>"><img style="width: 200px;" src="<?php echo $params['image_url']; ?>" /></a>
							</div>
						</div>
                                                <div class="clearfix">
							<label for="xlInput">Product Url</label>
							<div class="input">
								<input class='large disabled' name='product_url' value="<?php echo $params['product_url']; ?>" type='text'>
                                                                <a href="<?php echo $params['product_url']; ?>">Link</a>
							</div>
						</div>
                                                <div class="clearfix">
							<label for="xlInput">Status</label>
							<div class="input">
                                                            <select name="status">
                                                            <?php 
                                                                $statuses = array("new", "pending", "rejected", "approved");
                                                                foreach($statuses as $status){
                                                            ?>
                                                                <option value="<?php echo $status; ?>" <?php echo ($status == $params['status'] ? "selected": ''); ?>><?php echo $status; ?></option>
                                                            <?  } ?>
                                                            </select>
								
							</div>
						</div>
                                        </fieldset>

			        <fieldset>
			          <div class="actions">
			            <input type="submit" class="btn primary" value="Save changes">&nbsp;<button type="reset" class="btn back">Cancel</button>
			          </div>
			        </fieldset>
			      </form>
		  	</div>
		</div>

	</div>

</div>

<script>
    
    $('input[name=theme]').autocomplete( {source: <?php echo json_encode($this->themes); ?>} );
    $('input[name=style]').autocomplete( {source: <?php echo json_encode($this->styles); ?>} );
    $('input[name=tpye]').autocomplete( {source: <?php echo json_encode($this->types); ?>} );
</script>
