<?php
?>

<div class="left">

	<div class="content">

		<div class="page-header">
			<h3>
		  		Listing '<?php echo ($this->filter? $this->filter: 'All');?>' <?php echo $this->model; ?>s <small></small> <span class='right'><a href='/admin/<?php echo strtolower($this->model); ?>?type=<?php echo $this->params('type'); ?>'>Add a <?php echo strtolower($this->model); ?></a></span>
		  	</h3>
		</div>

		<div class="row">
                    <div>
                    <form id="filter" action="/admin/products/filter/<?php echo $this->filter; ?>">
                        <select id="gender_filter" name="gender">
                            <option value="">None</option>
                            <option value="m" <?php echo ( $this->params('gender') == 'm' ? "selected" : ''); ?>>Male</option>
                            <option value="f" <?php echo ( $this->params('gender') == 'f' ? "selected" : ''); ?>>Female</option>
                        </select>
                        <input type="submit" class="btn secondary" value="filter">
                    </form>
                        
                    </div>
		  	<div class="span12">
		    	<?php echo $this->pager($this->data->pager(), 'partials/pager/text_only.phtml'); ?>
		  	</div>
		</div>

		<div class="row">
		  	<div class="span15">
		  		<table>
			        <thead>
			          <tr>
			            <th class="header" rel="product.product_id">#</th>
                                    <th class="header" rel="product.style">Theme</th>
                                    <th class="header" rel="product.style">Style</th>
			            <th class="header" rel="product.type">Type</th>
			            <th class="header" rel="product.gender">Gender</th>
                                    <th class="header" rel="product.price">Price</th>
                                    <th class="header" rel="product.brand">Brand</th>
                                    <th class="header" rel="product.image_url">Image</th>
			            <th class="header">Action</th>
			          </tr>
			        </thead>
			        <tbody>
			        <?php foreach($this->data->rows() AS $key=>$value){ ?>
			        <tr>
			            <td><?php echo $value['product_id']; ?></td>
                                    <td><?php echo $value['theme']; ?></td>
                                    <td><?php echo $value['style']; ?></td>
			            <td><?php echo $value['type']; ?></td>
			            <td><?php echo $value['gender']; ?></td>
                                    
                                    <td><?php echo $value['price']; ?></td>
                                    <td><?php echo $value['brand']; ?></td>
                                    <td><img style="width: 180px" src="<?php echo $value['image_url']; ?>"/></td>
			            <td>
			            	<a href="/admin/<?php echo strtolower($this->model); ?>/id/<?php echo $value[strtolower($this->model).'_id']; ?>?redir=<?php echo $this->redir; ?>" class="btn blue">Edit</a>
			            	<a href="/admin/delete/?model=<?php echo $this->model; ?>&id=<?php echo $value[strtolower($this->model).'_id'];; ?>" class="btn red trig_delete" rel="model=<?php echo $this->model; ?>|id=<?php echo $value[$this->primary]; ?>">Remove</a>
			            </td>
			          </tr>
			          <?php } ?>
			          </tbody>
			      </table>

			     <?php echo $this->pager($this->data->pager(), 'partials/pager/pager.phtml'); ?>
		  	</div>



		</div>

	</div>

</div>

<script>
    $('#gender_filter').change( function(e){
        $this = $(this);
        gender = $this.val();
        window.location('?gender=') 
    });
</script>