<?php
?>

<div class="left">

	<div class="content">

		<div class="page-header">
			<h3>
		  		Listing all <?php echo $this->model; ?>s <small></small> <span class='right'><a href='/admin/<?php echo strtolower($this->model); ?>?type=<?php echo $this->params('type'); ?>'>Add a <?php echo strtolower($this->model); ?></a></span>
		  	</h3>
		</div>

		<div class="row">
		  	<div class="span12">
		    	<?php echo $this->pager($this->data->pager(), 'partials/pager/text_only.phtml'); ?>
		  	</div>
		</div>

		<div class="row">
		  	<div class="span15">
				<div>
					<p>
						By Type:
						<select class="filter dropdown" rel="type">
							<?php echo $this->dropdownOptions(array(
								"",
								"Post"	=>	"Post",
							), $this->params('type', 'Post'));
							?>
						</select>
					</p>
				</div>
		  		<table>
			        <thead>
			          <tr>
			            <th class="header" rel="product.product_id">#</th>
			            <th class="header" rel="product.type">Type</th>
			            <th class="header" rel="product.gender">Gender</th>
			            <th class="header" rel="product.style">Style</th>
                                    <th class="header" rel="product.price">Price</th>
                                    <th class="header" rel="product.brand">Brand</th>
                                    <th class="header" rel="product.image_url">Image</th>
			            <th class="header">Action</th>
			          </tr>
			        </thead>
			        <tbody>
			        <?php foreach($this->data->rows() AS $key=>$value){ ?>
			        <tr>
			            <td><?php echo $value['product_id']; ?></td>
			            <td><?php echo $value['type']; ?></td>
			            <td><?php echo $value['gender']; ?></td>
                                    <td><?php echo $value['style']; ?></td>
                                    <td><?php echo $value['price']; ?></td>
                                    <td><?php echo $value['brand']; ?></td>
                                    <td><img style="width: 200px" src="<?php echo $value['image_url']; ?>"/></td>
			            <td><?php echo date("m/d/y", strtotime($value['created'])); ?></td>
			            <td>
			            	<a href="/admin/<?php echo strtolower($this->model); ?>/id/<?php echo $value[strtolower($this->model).'_id']; ?>" class="btn blue">Edit</a>
			            	<a href="/admin/delete/?model=<?php echo $this->model; ?>&id=<?php echo $value[strtolower($this->model).'_id'];; ?>" class="btn red trig_delete" rel="model=<?php echo $this->model; ?>|id=<?php echo $value[$this->primary]; ?>">Remove</a>
			            </td>
			          </tr>
			          <?php } ?>
			          </tbody>
			      </table>

			     <?php echo $this->pager($this->data->pager(), 'partials/pager/pager.phtml'); ?>
		  	</div>



		</div>

	</div>

</div>

