<?php foreach($this->products as $product){ ?>
	<li class="col2">
                <a href="<?php echo $product['product_url']; ?>" class="item" target="_blank">
                        <img src="<?php echo $product['image_url']; ?>" alt="" />
                        <div class="price">$<?php echo $product['price']; ?></div>
                        <div class="rating"></div>
                        <div class="current-rating">33 likes</div>
                        <button class="like-button">Like It</button>
                </a>
                <div class="item-overlay">
                        <div class="like-buttons">
                                <div class="thumbs-up"></div>
                                <div class="thumbs-down"></div>
                        </div>
                        <div class="save-for-later"></div>
                </div>
	</li>
<?php } ?>