<?php foreach($this->products as $product){ ?>
	<li class="col2" data-product_id="<?php echo $product['product_id']; ?>">
                <a href="<?php echo $product['product_url']; ?>" class="item" target="_blank">
                        <img src="<?php echo $product['image_url']; ?>" alt="" />
                        <div class="price">$<?php echo $product['price']; ?></div>
                </a>
                <div class="rating"></div>
                <span class="current-rating"><?php echo $product['like_count']; ?></span>
                <div data-prod_id="<?php echo $product['product_id']; ?>" class="like-button"></div>
	</li>
<?php } ?>